### ISSUE TITLE
About annotations

### ISSUE THREAD

**Issue by zhiyuanyou** [2Obe/BSData#3]
Hi~ 
Thanks for your good dataset and annotations.
I want to verify that if one image gets no annotations, it is because (a) **this image contains no defects** or (b) **it is just not annotated?**

**Comment by 2Obe** [comment]
Than you for your comment! If you can tell me about which image your comment is, I can better help you.

**Comment by zhiyuanyou** [comment]
Thanks. 

Like *01_200905161959_635000_270_crop_2.jpg*, *01_200916071922_635000_270_crop_1.jpg*, and so on. 

Their annotations in *image_data.json* both are **null** (shown as follows). I wonder if (1) **these images contain no defects** or (b) **these images are not annotated?**

        {
            "filename": "01_200905161959_635000_270_crop_2.jpg",
            "train_test_split": null,
            "type": 2,
            "wear_dev": [
                "01_200908225742_635000_270_crop",
                "01_200908233905_635000_270_crop"
            ],
            "annotations": null
        },
        {
            "filename": "01_200916071922_635000_270_crop_1.jpg",
            "train_test_split": null,
            "type": 2,
            "wear_dev": [
                "01_200908225742_635000_270_crop",
                "01_200908233905_635000_270_crop"
            ],
            "annotations": null
        }

**Comment by sungsy** [comment]
Sorry for the late answer! 
It is possible that some images, like those you mention, do not contain annotations, since there is no surface defect visible. This is because the dataset also contains the ```wear_dev_split``` - 27 wear developments. 
I hope this answers the question.
