### ISSUE TITLE
Code for Visualzation of Annotation

### ISSUE THREAD

**Issue by dragonlee258079** [2Obe/BSData#4]
Hi, thank you for provide very useful surface defect detection dataset. Could you please further provide the code to visual the annotation  representated via json so that we can utilize the dataset more convenient? Thank you very much.

**Comment by sungsy** [comment]
Sorry for the late answer!
I hope I understand your question correctly. To overlay the annotations over the image [labelme](https://github.com/wkentaro/labelme) should work.
