### ISSUE TITLE
Request for Authorization to Use BSData Dataset in Research

### ISSUE THREAD

**Issue by Fiwid** [2Obe/BSData#7]
Dear Professor,
I am Jiawei Chen, a graduate student from the School of Mechatronics and Control Engineering at Shenzhen University. Our team is currently engaged in research on industrial vision and intelligent systems. We are working on a research project aimed at collecting multiple original industrial datasets and integrating them into a large dataset for research and experimentation purposes.

In our quest for high-quality and diverse original industrial data, we came across your BSData dataset and were highly intrigued by it. The quality of this dataset make it an ideal choice for our research. We plan to integrate this dataset into our research work and may apply for relevant knowledge licenses.

To ensure the legitimacy of our research work, we plan to apply for the necessary intellectual property licenses. Therefore, we are reaching out through this email to request your authorization to redistribute your BSData dataset and incorporate it into our comprehensive dataset. We fully understand and respect your concerns regarding the intellectual property of the dataset, and we are willing to adhere to any specifications and conditions you may have. We commit to using the dataset for academic research purposes and will appropriately cite and acknowledge your work in our publications and research reports.

If you require additional information or if we can provide you with a more detailed research plan, please feel free to let us know. We look forward to your response and sincerely appreciate your attention to our request.

Thank you very much for your time and cooperation.

Best regards,

Jiawei Chen
Shenzhen University

**Comment by sungsy** [comment]
Hi Jiawei Chen, 
we discussed your request. Yes, you can use the BSData dataset in your research work.

Sincerely
the authors
